use prost_reflect::{DescriptorPool, DynamicMessage, ReflectMessage, Value};
use std::path::{Path, PathBuf};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let proto_root = PathBuf::from(&manifest_dir).join("../../proto");
    let proto_root = proto_root
        .canonicalize()
        .map_err(|e| format!("proto root not found at {}: {}", proto_root.display(), e))?;

    let walletrpc = proto_root.join("walletrpc.proto");
    let walletrpc = walletrpc
        .canonicalize()
        .map_err(|e| format!("walletrpc.proto not found at {}: {}", walletrpc.display(), e))?;

    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);
    let descriptor_path = out_dir.join("walletrpc.bin");

    tonic_build::configure()
        .file_descriptor_set_path(&descriptor_path)
        .compile(&[walletrpc.as_path()], &[proto_root.as_path()])?;

    let descriptor_bytes = std::fs::read(&descriptor_path)?;
    pbjson_build::Builder::new()
        .register_descriptors(&descriptor_bytes)?
        .build(&[".walletrpc"])?;

    generate_http_router(&descriptor_bytes, &out_dir)?;

    println!("cargo:rerun-if-changed={}", walletrpc.display());
    println!("cargo:rerun-if-changed={}", proto_root.display());
    Ok(())
}

fn generate_http_router(
    descriptor_bytes: &[u8],
    out_dir: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let pool = DescriptorPool::decode(descriptor_bytes)?;
    let http_ext = pool
        .get_extension_by_name("google.api.http")
        .ok_or("google.api.http extension missing from descriptor pool")?;

    let mut routes: Vec<Route> = Vec::new();
    for service in pool.services() {
        if service.full_name() != "walletrpc.WalletService" {
            continue;
        }
        for method in service.methods() {
            let opts = method.options();
            if !opts.has_extension(&http_ext) {
                continue;
            }
            let val = opts.get_extension(&http_ext);
            let rule = match val.as_ref() {
                Value::Message(m) => m.clone(),
                _ => return Err("google.api.http option is not a message".into()),
            };
            let (verb, path) = extract_verb_path(&rule)?;
            if verb != "post" {
                return Err(format!(
                    "method {} uses unsupported HTTP verb {} (only POST supported)",
                    method.full_name(),
                    verb
                )
                .into());
            }

            let rust_method = camel_to_snake(method.name());
            let req_type = method
                .input()
                .name()
                .to_string();
            let resp_type = method
                .output()
                .name()
                .to_string();
            let handler = format!("{}_handler", rust_method);

            routes.push(Route {
                path,
                rust_method,
                handler,
                req_type,
                resp_type,
            });
        }
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs - do not edit\n");
    out.push_str("// Included via include! into src/http.rs; relies on its imports.\n\n");

    out.push_str("pub fn http_router(svc: Arc<WalletRPC>) -> Router {\n");
    out.push_str("    Router::new()\n");
    for r in &routes {
        out.push_str(&format!(
            "        .route({:?}, post({}))\n",
            r.path, r.handler
        ));
    }
    out.push_str("        .with_state(svc)\n");
    out.push_str("}\n\n");

    for r in &routes {
        out.push_str(&format!(
            "async fn {handler}(\n\
             \x20   State(svc): State<Arc<WalletRPC>>,\n\
             \x20   Json(req): Json<pb::{req_type}>,\n\
             ) -> Result<Json<pb::{resp_type}>, HttpError> {{\n\
             \x20   let resp = svc.{rust_method}(tonic::Request::new(req)).await?;\n\
             \x20   Ok(Json(resp.into_inner()))\n\
             }}\n\n",
            handler = r.handler,
            req_type = r.req_type,
            resp_type = r.resp_type,
            rust_method = r.rust_method,
        ));
    }

    std::fs::write(out_dir.join("http_routes.rs"), out)?;
    Ok(())
}

struct Route {
    path: String,
    rust_method: String,
    handler: String,
    req_type: String,
    resp_type: String,
}

fn extract_verb_path(
    rule: &DynamicMessage,
) -> Result<(String, String), Box<dyn std::error::Error>> {
    let desc = rule.descriptor();
    for verb in ["get", "put", "post", "delete", "patch"] {
        let field = desc
            .get_field_by_name(verb)
            .ok_or_else(|| format!("HttpRule missing {} field", verb))?;
        if rule.has_field(&field) {
            let val = rule.get_field(&field);
            let path = val
                .as_str()
                .ok_or("HTTP path was not a string")?
                .to_string();
            return Ok((verb.to_string(), path));
        }
    }
    Err("no HTTP verb set on HttpRule".into())
}

fn camel_to_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            for lc in c.to_lowercase() {
                out.push(lc);
            }
        } else {
            out.push(c);
        }
    }
    out
}
